# Playing around with PyG: PyTorch Geometric

In [1]:
import torch

from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GCNConv, Sequential
from torch_geometric.utils import to_dense_batch

/home/sam/.virtualenvs/pvg-experiments/lib/python3.11/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/sam/.virtualenvs/pvg-experiments/lib/python3.11/site-packages/torch_sparse/_spmm_cpu.so: undefined symbol: _ZN5torch8autograd13_wrap_outputsERKSt6vectorIN2at6TensorESaIS3_EERKSt13unordered_setIPN3c1010TensorImplESt4hashISB_ESt8equal_toISB_ESaISB_EESJ_NS9_8ArrayRefINS9_8optionalIS3_EEEERKSt10shared_ptrINS0_4NodeEESt8functionIFS5_S5_S5_EE
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
/home/sam/.virtualenvs/pvg-experiments/lib/python3.11/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch

In [2]:
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=False)

In [3]:
dataset._data

Data(x=[19580, 21], edge_index=[2, 74564], y=[600])

In [4]:
dataset.slices.keys()

dict_keys(['edge_index', 'x', 'y'])

In [5]:
dataset.num_node_attributes

18

In [6]:
dataset[0]["x"].shape

torch.Size([37, 21])

In [7]:
batch = next(iter(loader))
batch

DataBatch(edge_index=[2, 4264], x=[1069, 21], y=[32], batch=[1069], ptr=[33])

In [8]:
to_dense_batch(batch.x, batch.batch)[1].shape

torch.Size([32, 88])

In [9]:
GCNConv(21, 32)(batch.x, batch.edge_index)

tensor([[ 8.6978,  2.1233,  7.5288,  ..., -3.1112, 15.7092, 15.4804],
        [ 8.5417,  2.1621,  7.3531,  ..., -2.5585, 15.2704, 15.2754],
        [ 8.8853,  2.1759,  7.7182,  ..., -2.0378, 15.8727, 16.0194],
        ...,
        [ 4.8199,  1.8186,  3.7956,  ..., -0.0919,  7.3434,  8.2824],
        [ 5.9911,  1.9050,  5.3107,  ...,  0.4865,  9.7670, 10.8726],
        [ 6.2406,  2.1481,  5.6617,  ...,  0.1001, 10.1008, 11.2041]],
       grad_fn=<AddBackward0>)

In [10]:
a = torch.rand(3, 2, 4)
a

tensor([[[0.1611, 0.9995, 0.6376, 0.9370],
         [0.2763, 0.9788, 0.8231, 0.3333]],

        [[0.0415, 0.5171, 0.3982, 0.3930],
         [0.5470, 0.1693, 0.3270, 0.4368]],

        [[0.3078, 0.0533, 0.5840, 0.9654],
         [0.0705, 0.5151, 0.7985, 0.0534]]])

In [11]:
a[torch.tensor([0, 1, 2]), torch.tensor([1, 0, 1]), torch.tensor([2, 1, 3])]#[torch.tensor([False, True, True])]

tensor([0.8231, 0.5171, 0.0534])

In [12]:
b = torch.rand(4,5)
b

tensor([[0.3844, 0.7475, 0.7136, 0.7143, 0.4429],
        [0.9129, 0.0809, 0.2757, 0.5286, 0.3061],
        [0.5498, 0.4385, 0.2171, 0.0993, 0.8366],
        [0.9360, 0.8727, 0.4817, 0.5353, 0.8881]])

In [13]:
b[torch.tensor([1, 3]), torch.tensor([1, 3])]

tensor([0.0809, 0.5353])

In [17]:
type(batch[:10][0])

torch_geometric.data.data.Data

In [19]:
batch.y

AttributeError: 'GlobalStorage' object has no attribute 'wl_score'